### ISSUE TITLE
In the client, it should not be possible to update a lobby to a ranked lobby, if there are unregistered users in the lobby and I want to be informed that this is not allowed

### ISSUE THREAD

**Issue by apple00juice** [sopra-fs22-group-16/sopra-fs22-group-16-client#155]

**Comment by apple00juice** [comment]
I think, I will add a boolean field registered to the members of the memberList of the LobbyGetDTO such that you know if there are unregistered users.

**Comment by luis-tm** [comment]
Closed by forbid non register users to choose ranked games #165
